version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d analytics -u postgres"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always

    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root

    ports:
      - "5050:80"

  backend:
    build:
      context: ./django_backend
    command: gunicorn links.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

    depends_on:
      - db

  frontend:
    build:
      context: ./react_frontend
    volumes:
      - react_build:/react/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
